### ISSUE TITLE
Override quality of images

### ISSUE THREAD

**Issue by paarals** [PEMB2030/decidim-capitalofdemocracy-barcelona#20]
Media is pixeled when you aren't previewing: https://capitalofdemocracy.barcelona/conferences/futureforcitizens/media 

![imatge](https://github.com/PEMB2030/decidim-capitalofdemocracy-barcelona/assets/40388743/c87d06f8-910e-47a4-b7b3-29518805d9ff)

- [x] Apply override "thumbnail"

**Comment by microstudi** [comment]
done!
